name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_REGISTRY_SECRET }}

    - name: Build+publish Docker image
      run: |
        docker build --tag ghcr.io/marcelb98/tempsrvr:latest .
        docker push ghcr.io/marcelb98/tempsrvr:latest
