name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_REGISTRY_SECRET }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/marcelb98/tempSrvr:latest
        docker run ghcr.io/marcelb98/tempSrvr:latest
        docker push ghcr.io/marcelb98/tempSrvr:latest
